version: 2
jobs:
  build:
    docker:
      - image: minepicco/cc-build-image:1.0
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: GET CloudFormation template
          command: cat 0_high_alert.template > demo.template
          # command: cat 1_high_alert.template > demo.template
      - run:
          name: GET audit result
          command: |
              curl --data-binary @demo.template -X POST https://scanapi.redlock.io/v1/iac > output.json
              result=`cat output.json| jq .result.severity_stats.high`
              if [ $result -gt 0 ]; then 
                  echo "You have "$result" high alert(s).";
                  cat output.json | jq  '.result.rules_matched[] | select(.severity == "high")| .name';
                  exit 1; 
              else 
                  echo "No high alert was detected"; 
              fi;

